name: event_book_app
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  go_router: ^14.2.1
  flutter_screenutil: ^5.9.3
  google_fonts: ^6.2.1
  flutter_native_splash: ^2.4.1
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
